# Generated by Django 4.2.3 on 2023-09-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angelfire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='signature',
            field=models.CharField(default='Earth, Wind and Angelfire', max_length=140),
        ),
    ]
